spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/javaee?characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456
  jpa:
    show-sql: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123456
      timeout: 2000ms
      repositories:
        enabled: false
      lettuce:
        pool:
          max-active: 8        # 连接池的最大连接数
          max-idle: 8          # 连接池中最多的空闲连接数
          min-idle: 0          # 连接池中最少的空闲连接数
          max-wait: 1000ms     # 连接池获取连接时的最大等待时间

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demochapter05.entity
