spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/javaee?characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
  cache:
    jcache:
      config: classpath:ehcache.xml
#  cache:
#    type: redis
#    redis:
#      use-key-prefix: true
#      key-prefix: book_
#      cache-null-values: false
#      time-to-live: 400s

